### Start import
POST localhost:3000/api/v1/import

### GET Import status
GET localhost:3000/api/v1/import/status/:uuid


### GET products
GET localhost:3000/api/v1/products
Content-Type: application/json
